version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 127.0.0.1:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app

